version: '3.4'
services:
  app:
    image: deploy-docker:laravel
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8012:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
